package com.recapmaster.app.auth

import android.content.Context
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

object AuthManager {

    private val auth: FirebaseAuth by lazy { FirebaseAuth.getInstance() }

    private val _currentUser = MutableStateFlow<FirebaseUser?>(null)
    val currentUser: StateFlow<FirebaseUser?> = _currentUser.asStateFlow()

    init {
        try {
            _currentUser.value = auth.currentUser
            auth.addAuthStateListener { firebaseAuth ->
                _currentUser.value = firebaseAuth.currentUser
            }
        } catch (t: Throwable) {
            t.printStackTrace()
        }
    }

    /**
     * Retrieves the OAuth Web Client ID generated by Google Services.
     * Looks up R.string.default_web_client_id dynamically so compilation does not fail if missing.
     */
    fun getWebClientId(context: Context): String? {
        return try {
            val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
            if (resId != 0) context.getString(resId) else null
        } catch (_: Throwable) {
            null
        }
    }

    /**
     * Builds the GoogleSignInClient using the resolved webClientId.
     */
    fun getGoogleSignInClient(context: Context, webClientId: String?): GoogleSignInClient {
        val builder = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestEmail()

        if (!webClientId.isNullOrBlank()) {
            builder.requestIdToken(webClientId)
        }

        return GoogleSignIn.getClient(context, builder.build())
    }

    /**
     * Authenticates with Firebase using the Google ID Token.
     */
    fun signInWithGoogleIdToken(
        idToken: String,
        onSuccess: (FirebaseUser) -> Unit,
        onError: (String) -> Unit
    ) {
        val credential = GoogleAuthProvider.getCredential(idToken, null)
        auth.signInWithCredential(credential)
            .addOnSuccessListener { result ->
                val user = result.user
                if (user != null) {
                    _currentUser.value = user
                    onSuccess(user)
                } else {
                    onError("Failed to obtain Firebase user session.")
                }
            }
            .addOnFailureListener { exception ->
                onError(exception.localizedMessage ?: "Firebase Google Sign-In failed.")
            }
    }

    /**
     * Signs out the user from Firebase and Google.
     */
    fun signOut(context: Context, onComplete: () -> Unit = {}) {
        try {
            auth.signOut()
            val webClientId = getWebClientId(context)
            getGoogleSignInClient(context, webClientId).signOut().addOnCompleteListener {
                _currentUser.value = null
                onComplete()
            }
        } catch (_: Throwable) {
            _currentUser.value = null
            onComplete()
        }
    }
}
